'use client';

import Link from 'next/link';
import { Calendar, Scale, FileText, ListChecks } from 'lucide-react';
import { SearchResultsGrouped } from '@/lib/search';
import React from "react";

interface SearchResultsProps {
  results: SearchResultsGrouped;
  query: string;
}

interface ResultSectionProps {
  title: string;
  icon: React.ReactNode;
  results: Array<{
    entity_type: string;
    entity_id: string;
    title: string;
    snippet: string;
    rank: number;
  }>;
  baseUrl: string;
  color: string;
}

function ResultSection({ title, icon, results, baseUrl, color }: ResultSectionProps) {
  if (results.length === 0) return null;

  return (
    <section aria-labelledby={`section-${title.toLowerCase()}`}>
      <h2
        id={`section-${title.toLowerCase()}`}
        className={`flex items-center gap-2 text-lg font-semibold mb-3 ${color}`}
      >
        {icon}
        {title}
        <span className="text-sm font-normal text-slate-500">({results.length})</span>
      </h2>
      <ul className="space-y-3" role="list">
        {results.map((result) => (
          <li key={`${result.entity_type}-${result.entity_id}`}>
            <Link
              href={`${baseUrl}#${result.entity_id}`}
              className="block p-4 bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 hover:border-emerald-300 dark:hover:border-emerald-600 hover:shadow-md transition group"
            >
              <h3 className="font-medium text-slate-900 dark:text-white group-hover:text-emerald-600 dark:group-hover:text-emerald-400 transition">
                {result.title}
              </h3>
              {result.snippet && (
                /**
                 * SECURITY: Safe to use dangerouslySetInnerHTML here because:
                 * 1. The <mark> tags are generated by our FTS5 snippet() function
                 * 2. The underlying content comes from our own database
                 * 3. User input cannot inject HTML - it's sanitized before FTS5 indexing
                 * 4. The stripMarkdown() function in search.ts removes markdown but preserves <mark>
                 */
                <p
                  className="text-sm text-slate-600 dark:text-slate-400 mt-1 line-clamp-2"
                  dangerouslySetInnerHTML={{ __html: result.snippet }}
                />
              )}
            </Link>
          </li>
        ))}
      </ul>
    </section>
  );
}

export default function SearchResults({ results, query }: SearchResultsProps) {
  if (results.total === 0) {
    return (
      <div className="text-center py-12" role="status" aria-live="polite">
        <div className="text-slate-400 mb-4">
          <svg
            className="w-16 h-16 mx-auto"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
            />
          </svg>
        </div>
        <h2 className="text-xl font-semibold text-slate-700 dark:text-slate-300">
          No results found
        </h2>
        <p className="text-slate-500 mt-2">
          No matches for &ldquo;<span className="font-medium">{query}</span>&rdquo;. Try different keywords.
        </p>
        <div className="mt-6 text-sm text-slate-500">
          <p>Search tips:</p>
          <ul className="mt-2 space-y-1">
            <li>Use fewer or more general terms</li>
            <li>Check your spelling</li>
            <li>Try searching for ordinance numbers (e.g., &ldquo;773&rdquo;)</li>
          </ul>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8" role="region" aria-label="Search results">
      {/* Summary */}
      <p className="text-slate-600 dark:text-slate-400" role="status" aria-live="polite">
        Found <span className="font-semibold text-slate-900 dark:text-white">{results.total}</span> results
        for &ldquo;<span className="font-medium">{query}</span>&rdquo;
      </p>

      {/* Results grouped by type */}
      <div className="grid gap-8 md:grid-cols-2">
        <div className="space-y-8">
          <ResultSection
            title="Meetings"
            icon={<Calendar className="w-5 h-5" aria-hidden="true" />}
            results={results.meetings}
            baseUrl="/meetings"
            color="text-blue-600 dark:text-blue-400"
          />
          <ResultSection
            title="Ordinances"
            icon={<Scale className="w-5 h-5" aria-hidden="true" />}
            results={results.ordinances}
            baseUrl="/ordinances"
            color="text-emerald-600 dark:text-emerald-400"
          />
        </div>
        <div className="space-y-8">
          <ResultSection
            title="Resolutions"
            icon={<FileText className="w-5 h-5" aria-hidden="true" />}
            results={results.resolutions}
            baseUrl="/resolutions"
            color="text-purple-600 dark:text-purple-400"
          />
          <ResultSection
            title="Agenda Items"
            icon={<ListChecks className="w-5 h-5" aria-hidden="true" />}
            results={results.agenda_items}
            baseUrl="/meetings"
            color="text-amber-600 dark:text-amber-400"
          />
        </div>
      </div>
    </div>
  );
}
